services:
  paroo:
    image: ghcr.io/shoshtari/paroo
    pull_policy: always
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - paroo-db

  paroo-db:
    image: postgres:16
    restart: always
    command: -c 'max_connections=200'
